spring:
  application:
    name: zuul-server



server:
  port: 5555
  use-forward-headers: true


eureka:
  client:
    serviceUrl:
      defaultZone: "http://admin:epxing@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka"
  instance:
    prefer-ip-address: true



zuul:
  routes:
    client-demo:
      path: /demo/**
      serviceId: client-demo
    auth-server:
      path: /auth/**
      serviceId: auth-server
      stripPrefix: true
  sensitive-headers: Cookie,Set-Cookie



security:
  oauth2:
    client:
      access-token-uri: http://localhost:7777/auth/oauth/token
      user-authorization-uri: http://localhost:7777/auth/oauth/authorize
      client-id: epxing-auth
      client-secret: epxing
#      grant-type: password
      grant-type: authorization_code
    resource:
      jwt:
        key-value: epxing
    sso:
      login-path: /auth-server/auth/login
    authorization:
      check-token-access:  http://localhost:7777/auth/oauth/check_token



logging:
  level:
    org.springframework.security: debug
    com.netflix: DEBUG


# logback日志配置,日志环境类型，服务名，级别
log.env.profile: dev
log.env.module: epxing-zuul
log.env.logger.level: info